version: '3.3'
services:
  corgibot:
    image: zate75/corgibot:latest
    command: /corgibot
    networks:
     - default
    logging:
      driver: json-file
    secrets:
     - botkey
networks:
  default:
    driver: overlay
secrets:
  botkey:
    external: true